kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: replicaset-ex
  labels:
    app: replicaSetExample
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: sampleapipod
      labels:
        app: sampleapi
        tier: frontend
    spec:
      containers:
        - name: sampleapi
          image: dishantanand/sampleapi:v1
          ports:
            - containerPort: 8090